# Generated by Django 5.2.7 on 2025-10-15 01:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name='Pergunta')),
                ('image', models.URLField(blank=True, help_text='URL da imagem da pergunta (opcional - use Cloudinary)', max_length=500, null=True)),
                ('explanation', models.TextField(blank=True, help_text='Explicação da resposta correta')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['quiz', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Fácil'), ('medium', 'Médio'), ('hard', 'Difícil')], default='medium', max_length=10)),
                ('country', models.CharField(choices=[('en-US', '🇺🇸 United States'), ('en-CA', '🇨🇦 Canada'), ('es-MX', '🇲🇽 Mexico'), ('en-GB', '🇬🇧 United Kingdom'), ('de-DE', '🇩🇪 Germany'), ('fr-FR', '🇫🇷 France'), ('es-ES', '🇪🇸 Spain'), ('it-IT', '🇮🇹 Italy'), ('nl-NL', '🇳🇱 Netherlands'), ('sv-SE', '🇸🇪 Sweden'), ('no-NO', '🇳🇴 Norway'), ('pl-PL', '🇵🇱 Poland'), ('pt-PT', '🇵🇹 Portugal'), ('en-IN', '🇮🇳 India'), ('en-PH', '🇵🇭 Philippines'), ('id-ID', '🇮🇩 Indonesia'), ('ja-JP', '🇯🇵 Japan'), ('ko-KR', '🇰🇷 South Korea'), ('th-TH', '🇹🇭 Thailand'), ('vi-VN', '🇻🇳 Vietnam'), ('en-AU', '🇦🇺 Australia'), ('en-NZ', '🇳🇿 New Zealand'), ('pt-BR', '🇧🇷 Brazil'), ('es-AR', '🇦🇷 Argentina'), ('es-CO', '🇨🇴 Colombia')], default='pt-BR', help_text='País do quiz', max_length=10)),
                ('time_limit', models.IntegerField(default=0, help_text='Tempo limite em segundos (0 = sem limite)')),
                ('active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'ordering': ['theme', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=500, verbose_name='Alternativa')),
                ('is_correct', models.BooleanField(default=False, verbose_name='É a resposta correta?')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.question')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
                'ordering': ['question', 'order'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.quiz'),
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, help_text='Para usuários não logados', max_length=40)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('question_order', models.JSONField(default=list, help_text='Ordem das perguntas [uuid, uuid, ...]')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.IntegerField(default=0)),
                ('max_score', models.IntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quizzes.quiz')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quiz Attempt',
                'verbose_name_plural': 'Quiz Attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=255)),
                ('icon', models.URLField(blank=True, help_text='URL da imagem do ícone (PNG, SVG, etc - use Cloudinary)', max_length=500, null=True)),
                ('country', models.CharField(choices=[('en-US', '🇺🇸 United States'), ('en-CA', '🇨🇦 Canada'), ('es-MX', '🇲🇽 Mexico'), ('en-GB', '🇬🇧 United Kingdom'), ('de-DE', '🇩🇪 Germany'), ('fr-FR', '🇫🇷 France'), ('es-ES', '🇪🇸 Spain'), ('it-IT', '🇮🇹 Italy'), ('nl-NL', '🇳🇱 Netherlands'), ('sv-SE', '🇸🇪 Sweden'), ('no-NO', '🇳🇴 Norway'), ('pl-PL', '🇵🇱 Poland'), ('pt-PT', '🇵🇹 Portugal'), ('en-IN', '🇮🇳 India'), ('en-PH', '🇵🇭 Philippines'), ('id-ID', '🇮🇩 Indonesia'), ('ja-JP', '🇯🇵 Japan'), ('ko-KR', '🇰🇷 South Korea'), ('th-TH', '🇹🇭 Thailand'), ('vi-VN', '🇻🇳 Vietnam'), ('en-AU', '🇦🇺 Australia'), ('en-NZ', '🇳🇿 New Zealand'), ('pt-BR', '🇧🇷 Brazil'), ('es-AR', '🇦🇷 Argentina'), ('es-CO', '🇨🇴 Colombia')], default='pt-BR', help_text='País do tema', max_length=10)),
                ('primary_color', models.CharField(blank=True, help_text='Cor principal (ex: #3b82f6)', max_length=7, null=True)),
                ('secondary_color', models.CharField(blank=True, help_text='Cor secundária para gradiente (ex: #8b5cf6)', max_length=7, null=True)),
                ('icon_bg_color_1', models.CharField(blank=True, help_text='Cor 1 do background do ícone (ex: #dbeafe)', max_length=7, null=True)),
                ('icon_bg_color_2', models.CharField(blank=True, help_text='Cor 2 do background do ícone (ex: #e0e7ff)', max_length=7, null=True)),
                ('order', models.IntegerField(default=0, help_text='Ordem de exibição')),
                ('active', models.BooleanField(default=True)),
                ('card_background_image', models.URLField(blank=True, help_text='URL da imagem de background do CARD/CAIXA do tema (use Cloudinary)', max_length=500, null=True)),
                ('card_background_color', models.CharField(blank=True, help_text='Cor de fundo do CARD/CAIXA (ex: #FF0000 ou linear-gradient(...))', max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Tema pai (deixe vazio para categoria principal)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='quizzes.theme')),
            ],
            options={
                'verbose_name': 'Theme',
                'verbose_name_plural': 'Themes',
                'ordering': ['order', 'title'],
                'unique_together': {('slug', 'country')},
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='quizzes.theme'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Título do Produto')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('image_url', models.URLField(max_length=500, verbose_name='URL da Imagem (use Cloudinary)')),
                ('product_url', models.URLField(max_length=500, verbose_name='Link do Produto')),
                ('active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Ordem de exibição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='quizzes.theme')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['theme', 'order', 'title'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='quiz',
            unique_together={('theme', 'slug')},
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_correct', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='quizzes.quizattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.question')),
                ('selected_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.answer')),
            ],
            options={
                'verbose_name': 'User Answer',
                'verbose_name_plural': 'User Answers',
                'ordering': ['answered_at'],
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
