# Generated by Django 5.2.7 on 2025-10-18 02:08

from django.db import migrations, models


def clean_orphan_data(apps, schema_editor):
    """Limpa dados órfãos antes da migração"""
    UserAnswer = apps.get_model('quizzes', 'UserAnswer')
    QuizAttempt = apps.get_model('quizzes', 'QuizAttempt')
    Question = apps.get_model('quizzes', 'Question')
    Answer = apps.get_model('quizzes', 'Answer')
    
    print("🧹 Limpando dados órfãos...")
    
    # Deletar UserAnswers primeiro
    user_answers_count = UserAnswer.objects.count()
    UserAnswer.objects.all().delete()
    print(f"   ✅ {user_answers_count} UserAnswers deletados")
    
    # Deletar QuizAttempts
    quiz_attempts_count = QuizAttempt.objects.count()
    QuizAttempt.objects.all().delete()
    print(f"   ✅ {quiz_attempts_count} QuizAttempts deletados")
    
    # Deletar Answers
    answers_count = Answer.objects.count()
    Answer.objects.all().delete()
    print(f"   ✅ {answers_count} Answers deletados")
    
    # Deletar Questions
    questions_count = Question.objects.count()
    Question.objects.all().delete()
    print(f"   ✅ {questions_count} Questions deletados")
    
    print("✨ Limpeza concluída!")


def reverse_clean_orphan_data(apps, schema_editor):
    """Função reversa - não faz nada pois os dados foram deletados"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0001_initial"),
    ]

    operations = [
        # Limpar dados órfãos primeiro
        migrations.RunPython(clean_orphan_data, reverse_clean_orphan_data),
        
        # Remover completamente as foreign keys
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='quiz',
        ),
        
        # Remover o campo id do Quiz
        migrations.RemoveField(
            model_name="quiz",
            name="id",
        ),
        
        # Alterar slug para primary key
        migrations.AlterField(
            model_name="quiz",
            name="slug",
            field=models.SlugField(max_length=255, primary_key=True, serialize=False),
        ),
        
        # Recriar foreign key constraints com to_field='slug'
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey('Quiz', on_delete=models.CASCADE, related_name='questions', to_field='slug'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='quiz',
            field=models.ForeignKey('Quiz', on_delete=models.CASCADE, related_name='attempts', to_field='slug'),
        ),
    ]
