# Generated by Django 5.2.7 on 2025-10-15 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='theme',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='theme',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
