# Generated by Django 5.2.7 on 2025-10-18 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0001_initial"),
    ]

    operations = [
        # Primeiro, remover foreign key constraints temporariamente
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey('Quiz', on_delete=models.CASCADE, related_name='questions', db_constraint=False),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='quiz',
            field=models.ForeignKey('Quiz', on_delete=models.CASCADE, related_name='attempts', db_constraint=False),
        ),
        
        # Remover o campo id do Quiz
        migrations.RemoveField(
            model_name="quiz",
            name="id",
        ),
        
        # Alterar slug para primary key
        migrations.AlterField(
            model_name="quiz",
            name="slug",
            field=models.SlugField(max_length=255, primary_key=True, serialize=False),
        ),
        
        # Recriar foreign key constraints com to_field='slug'
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey('Quiz', on_delete=models.CASCADE, related_name='questions', to_field='slug'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='quiz',
            field=models.ForeignKey('Quiz', on_delete=models.CASCADE, related_name='attempts', to_field='slug'),
        ),
    ]
