# Generated by Django 5.2.7 on 2025-10-19 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0002_change_quiz_primary_key_to_slug"),
    ]

    operations = [
        # Primeiro, adicionar to_field='slug' nas foreign keys que referenciam QuizGroup
        migrations.AlterField(
            model_name="quiz",
            name="quiz_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Grupo de quizzes equivalentes (ex: mesmo quiz em vários idiomas)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quizzes",
                to="quizzes.quizgroup",
                to_field="slug",
            ),
        ),
        migrations.AlterField(
            model_name="quizgroupbadge",
            name="quiz_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="available_badges",
                to="quizzes.quizgroup",
                to_field="slug",
            ),
        ),
        migrations.AlterField(
            model_name="userbadge",
            name="quiz_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_achievements",
                to="quizzes.quizgroup",
                to_field="slug",
            ),
        ),
        # Agora remover o campo id e tornar slug a primary key
        migrations.RemoveField(
            model_name="quizgroup",
            name="id",
        ),
        migrations.AlterField(
            model_name="quizgroup",
            name="slug",
            field=models.SlugField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
