# Generated by Django 5.2.7 on 2025-10-12 07:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_question_answer_quiz_question_quiz_quizattempt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Título do Produto')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('image_url', models.URLField(max_length=500, verbose_name='URL da Imagem')),
                ('product_url', models.URLField(max_length=500, verbose_name='Link do Produto')),
                ('active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Ordem de exibição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='quizzes.theme')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['theme', 'order', 'title'],
            },
        ),
    ]
