# Generated by Django 5.2.7 on 2025-10-15 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_alter_theme_unique_together_alter_theme_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='question_sample_size',
            field=models.IntegerField(default=20, help_text='Número de questões aleatórias a serem selecionadas (0 = usar todas)'),
        ),
    ]
