# Generated by Django 5.2.7 on 2025-10-19 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0003_change_quizgroup_primary_key"),
    ]

    operations = [
        # Primeiro, adicionar o campo slug (não como primary key ainda)
        migrations.AddField(
            model_name="badge",
            name="slug",
            field=models.SlugField(max_length=255, unique=True, default='temp-slug'),
            preserve_default=False,
        ),
        # Agora alterar as foreign keys para usar slug
        migrations.AlterField(
            model_name="quizgroupbadge",
            name="badge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quiz_groups",
                to="quizzes.badge",
                to_field="slug",
            ),
        ),
        migrations.AlterField(
            model_name="userbadge",
            name="badge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_achievements",
                to="quizzes.badge",
                to_field="slug",
            ),
        ),
        # Remover o campo id
        migrations.RemoveField(
            model_name="badge",
            name="id",
        ),
        # Tornar slug a primary key
        migrations.AlterField(
            model_name="badge",
            name="slug",
            field=models.SlugField(max_length=255, primary_key=True, serialize=False),
        ),
    ]

