# Generated by Django 5.2.7 on 2025-10-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.URLField(blank=True, help_text='URL da imagem da pergunta (opcional)', null=True),
        ),
    ]
