# Generated by Django 5.2.7 on 2025-10-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_badge_quizgroup_alter_question_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizgroup',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Quiz Group', 'verbose_name_plural': 'Quiz Groups'},
        ),
        migrations.AddField(
            model_name='quizgroup',
            name='order',
            field=models.IntegerField(default=0, help_text='Ordem de exibição dos quizzes deste grupo'),
        ),
    ]
