# Generated by Django 5.2.7 on 2025-10-12 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_question_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Theme', 'verbose_name_plural': 'Themes'},
        ),
        migrations.AddField(
            model_name='theme',
            name='icon',
            field=models.CharField(default='📚', help_text='Emoji do tema', max_length=10),
        ),
        migrations.AddField(
            model_name='theme',
            name='order',
            field=models.IntegerField(default=0, help_text='Ordem de exibição'),
        ),
        migrations.AddField(
            model_name='theme',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Tema pai (deixe vazio para categoria principal)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='quizzes.theme'),
        ),
    ]
