# Generated by Django 5.2.7 on 2025-10-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_add_order_to_quizgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizgroup',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Fácil'), ('medium', 'Médio'), ('hard', 'Difícil')], default='medium', help_text='Dificuldade do grupo (aplicada a todos os quizzes do grupo)', max_length=10),
        ),
    ]
