# Generated by Django 5.2.7 on 2025-10-12 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_alter_theme_options_theme_icon_theme_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='points',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='points_earned',
        ),
    ]
