# Generated by Django 5.2.7 on 2025-10-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_remove_points_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='background_color',
            field=models.CharField(blank=True, help_text='Cor de fundo (ex: #FF0000 ou linear-gradient(...))', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='background_image',
            field=models.URLField(blank=True, help_text='URL da imagem de background do tema', null=True),
        ),
    ]
