# Generated by Django 5.2.7 on 2025-10-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_add_difficulty_to_quizgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='description_template',
            field=models.TextField(blank=True, help_text='Template de descrição com placeholders {sample_size} e {total}. Ex: "Identifique {sample_size} personagens de {total} disponíveis"'),
        ),
    ]
