# Generated by Django 5.2.7 on 2025-10-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_add_description_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='description_translations',
            field=models.JSONField(blank=True, default=dict, help_text='Traduções da descrição: {"pt-BR": "texto", "en-US": "text", ...}'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição (fallback)'),
        ),
    ]
