# Generated by Django 5.2.7 on 2025-10-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_add_theme_background_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='background_color',
            field=models.CharField(blank=True, help_text='Cor de fundo (ex: #FF0000 ou linear-gradient(...))', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='background_image',
            field=models.URLField(blank=True, help_text='URL da imagem de background do tema', max_length=250, null=True),
        ),
    ]
