# Generated by Django 5.2.7 on 2025-10-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0008_increase_background_fields_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='card_background_color',
            field=models.CharField(blank=True, help_text='Cor de fundo do CARD/CAIXA (ex: #FF0000 ou linear-gradient(...))', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='card_background_image',
            field=models.URLField(blank=True, help_text='URL da imagem de background do CARD/CAIXA do tema', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='background_color',
            field=models.CharField(blank=True, help_text='Cor de fundo da PÁGINA (ex: #FF0000 ou linear-gradient(...))', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='background_image',
            field=models.URLField(blank=True, help_text='URL da imagem de background da PÁGINA', max_length=250, null=True),
        ),
    ]
