# Generated by Django 5.2.7 on 2025-10-17 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0009_add_discount_percentage_to_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="theme",
            name="icon_bg_color_1",
        ),
        migrations.RemoveField(
            model_name="theme",
            name="icon_bg_color_2",
        ),
    ]
