# Generated by Django 5.2.7 on 2025-10-12 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0009_add_card_background_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='background_image',
        ),
    ]
