# Generated by Django 5.2.7 on 2025-10-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0010_remove_page_background_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='icon_svg',
            field=models.CharField(blank=True, help_text='Nome do arquivo SVG (ex: trophy, soccer, gamepad)', max_length=50, null=True),
        ),
    ]
