# Generated by Django 5.2.7 on 2025-10-17 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0010_remove_icon_bg_color_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="badge",
            name="max_time_seconds",
        ),
        migrations.RemoveField(
            model_name="question",
            name="explanation",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="time_limit",
        ),
    ]
