# Generated by Django 5.2.7 on 2025-10-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0011_remove_unused_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="country",
            field=models.CharField(
                choices=[
                    ("en-US", "🇺🇸 United States"),
                    ("en-CA", "🇨🇦 Canada"),
                    ("es-MX", "🇲🇽 Mexico"),
                    ("en-GB", "🇬🇧 United Kingdom"),
                    ("es-ES", "🇪🇸 Spain"),
                    ("pt-PT", "🇵🇹 Portugal"),
                    ("en-IN", "🇮🇳 India"),
                    ("en-PH", "🇵🇭 Philippines"),
                    ("en-AU", "🇦🇺 Australia"),
                    ("en-NZ", "🇳🇿 New Zealand"),
                    ("pt-BR", "🇧🇷 Brazil"),
                    ("es-AR", "🇦🇷 Argentina"),
                    ("es-CO", "🇨🇴 Colombia"),
                ],
                default="pt-BR",
                help_text="País do quiz",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="country",
            field=models.CharField(
                choices=[
                    ("en-US", "🇺🇸 United States"),
                    ("en-CA", "🇨🇦 Canada"),
                    ("es-MX", "🇲🇽 Mexico"),
                    ("en-GB", "🇬🇧 United Kingdom"),
                    ("es-ES", "🇪🇸 Spain"),
                    ("pt-PT", "🇵🇹 Portugal"),
                    ("en-IN", "🇮🇳 India"),
                    ("en-PH", "🇵🇭 Philippines"),
                    ("en-AU", "🇦🇺 Australia"),
                    ("en-NZ", "🇳🇿 New Zealand"),
                    ("pt-BR", "🇧🇷 Brazil"),
                    ("es-AR", "🇦🇷 Argentina"),
                    ("es-CO", "🇨🇴 Colombia"),
                ],
                default="pt-BR",
                help_text="País do tema",
                max_length=10,
            ),
        ),
    ]
