# Generated by Django 5.2.7 on 2025-10-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0011_theme_icon_svg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='icon',
        ),
        migrations.AlterField(
            model_name='theme',
            name='icon_svg',
            field=models.CharField(blank=True, help_text='Nome do arquivo SVG (ex: trophy, soccer, gamepad, book, film, music)', max_length=50, null=True),
        ),
    ]
