# Generated by Django 5.2.7 on 2025-10-17 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0012_alter_quiz_country_alter_theme_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="question_sample_size",
            field=models.IntegerField(
                default=0,
                help_text="Número de questões aleatórias a serem selecionadas (0 = usar todas)",
            ),
        ),
    ]
