# Generated by Django 5.2.7 on 2025-10-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0012_remove_icon_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='icon_bg_color_1',
            field=models.CharField(blank=True, help_text='Cor 1 do background do ícone (ex: #dbeafe)', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='icon_bg_color_2',
            field=models.CharField(blank=True, help_text='Cor 2 do background do ícone (ex: #e0e7ff)', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='primary_color',
            field=models.CharField(blank=True, help_text='Cor principal (ex: #3b82f6)', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='secondary_color',
            field=models.CharField(blank=True, help_text='Cor secundária para gradiente (ex: #8b5cf6)', max_length=7, null=True),
        ),
    ]
