# Generated by Django 5.2.7 on 2025-10-18 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0013_alter_quiz_question_sample_size"),
    ]

    operations = [
        # Primeiro, remover foreign key constraints
        migrations.AlterField(
            model_name='theme',
            name='parent',
            field=models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='subcategories', db_constraint=False),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='theme',
            field=models.ForeignKey('Theme', on_delete=models.CASCADE, related_name='quizzes', db_constraint=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='theme',
            field=models.ForeignKey('Theme', on_delete=models.CASCADE, related_name='products', db_constraint=False),
        ),
        
        # Remover o campo id
        migrations.RemoveField(
            model_name="theme",
            name="id",
        ),
        
        # Alterar slug para primary key
        migrations.AlterField(
            model_name="theme",
            name="slug",
            field=models.SlugField(max_length=255, primary_key=True, serialize=False),
        ),
        
        # Recriar foreign key constraints
        migrations.AlterField(
            model_name='theme',
            name='parent',
            field=models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='subcategories'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='theme',
            field=models.ForeignKey('Theme', on_delete=models.CASCADE, related_name='quizzes'),
        ),
        migrations.AlterField(
            model_name='product',
            name='theme',
            field=models.ForeignKey('Theme', on_delete=models.CASCADE, related_name='products'),
        ),
    ]