# Generated by Django 5.2.7 on 2025-10-13 12:10

from django.db import migrations


def create_root_themes(apps, schema_editor):
    """
    Cria os temas raiz (categorias principais) com cores e ícones personalizados
    """
    Theme = apps.get_model('quizzes', 'Theme')
    
    # Dados dos temas raiz
    root_themes = [
        {
            'title': 'Esportes',
            'slug': 'esportes',
            'description': 'Teste seus conhecimentos sobre futebol, basquete, tênis e muito mais. De regras básicas a recordes históricos!',
            'icon_svg': 'sports',
            'primary_color': '#10b981',
            'secondary_color': '#059669',
            'icon_bg_color_1': '#d1fae5',
            'icon_bg_color_2': '#a7f3d0',
            'order': 1,
        },
        {
            'title': 'Entretenimento & Mídia',
            'slug': 'entretenimento-midia',
            'description': 'Filmes, séries, música e tudo sobre o mundo do entretenimento. De clássicos a lançamentos recentes!',
            'icon_svg': 'entertainment',
            'primary_color': '#8b5cf6',
            'secondary_color': '#7c3aed',
            'icon_bg_color_1': '#ede9fe',
            'icon_bg_color_2': '#ddd6fe',
            'order': 2,
        },
        {
            'title': 'Jogos',
            'slug': 'jogos',
            'description': 'Quizzes sobre videogames, jogos de tabuleiro e e-sports. De clássicos retrô a lançamentos modernos!',
            'icon_svg': 'games',
            'primary_color': '#ec4899',
            'secondary_color': '#db2777',
            'icon_bg_color_1': '#fce7f3',
            'icon_bg_color_2': '#fbcfe8',
            'order': 3,
        },
        {
            'title': 'Ciência & Tecnologia',
            'slug': 'ciencia-tecnologia',
            'description': 'Explore o universo da ciência, tecnologia e inovação. Física, química, biologia, astronomia e muito mais!',
            'icon_svg': 'science',
            'primary_color': '#06b6d4',
            'secondary_color': '#0891b2',
            'icon_bg_color_1': '#cffafe',
            'icon_bg_color_2': '#a5f3fc',
            'order': 4,
        },
        {
            'title': 'História',
            'slug': 'historia',
            'description': 'Viaje no tempo e teste seus conhecimentos sobre eventos históricos, civilizações antigas e personalidades marcantes!',
            'icon_svg': 'history',
            'primary_color': '#d97706',
            'secondary_color': '#b45309',
            'icon_bg_color_1': '#fef3c7',
            'icon_bg_color_2': '#fde68a',
            'order': 5,
        },
        {
            'title': 'Geografia',
            'slug': 'geografia',
            'description': 'Descubra o mundo através de países, capitais, bandeiras, montanhas e oceanos. Teste seu conhecimento global!',
            'icon_svg': 'geography',
            'primary_color': '#3b82f6',
            'secondary_color': '#2563eb',
            'icon_bg_color_1': '#dbeafe',
            'icon_bg_color_2': '#bfdbfe',
            'order': 6,
        },
        {
            'title': 'Arte & Cultura',
            'slug': 'arte-cultura',
            'description': 'Mergulhe no mundo das artes visuais, literatura, música clássica e movimentos culturais ao redor do mundo!',
            'icon_svg': 'art',
            'primary_color': '#a855f7',
            'secondary_color': '#9333ea',
            'icon_bg_color_1': '#f3e8ff',
            'icon_bg_color_2': '#e9d5ff',
            'order': 7,
        },
        {
            'title': 'Comida & Bebida',
            'slug': 'comida-bebida',
            'description': 'Explore o universo gastronômico! Culinária mundial, ingredientes, receitas e a cultura por trás dos pratos!',
            'icon_svg': 'food',
            'primary_color': '#f59e0b',
            'secondary_color': '#d97706',
            'icon_bg_color_1': '#fef3c7',
            'icon_bg_color_2': '#fde68a',
            'order': 8,
        },
        {
            'title': 'Natureza & Animais',
            'slug': 'natureza-animais',
            'description': 'Descubra a biodiversidade do planeta! Animais selvagens, ecossistemas, conservação e curiosidades da natureza!',
            'icon_svg': 'nature',
            'primary_color': '#22c55e',
            'secondary_color': '#16a34a',
            'icon_bg_color_1': '#dcfce7',
            'icon_bg_color_2': '#bbf7d0',
            'order': 9,
        },
        {
            'title': 'Política & Sociedade',
            'slug': 'politica-sociedade',
            'description': 'Entenda o mundo político e social. Governos, sistemas políticos, movimentos sociais e atualidades!',
            'icon_svg': 'politics',
            'primary_color': '#64748b',
            'secondary_color': '#475569',
            'icon_bg_color_1': '#f1f5f9',
            'icon_bg_color_2': '#e2e8f0',
            'order': 10,
        },
        {
            'title': 'Curiosidades Gerais',
            'slug': 'curiosidades-gerais',
            'description': 'Um pouco de tudo! Fatos curiosos, recordes mundiais, invenções e conhecimentos diversos para testar sua cultura geral!',
            'icon_svg': 'trivia',
            'primary_color': '#f43f5e',
            'secondary_color': '#e11d48',
            'icon_bg_color_1': '#ffe4e6',
            'icon_bg_color_2': '#fecdd3',
            'order': 11,
        },
        {
            'title': 'Celebridades & Personalidades',
            'slug': 'celebridades-personalidades',
            'description': 'Teste seus conhecimentos sobre celebridades, influenciadores, personalidades históricas e figuras públicas!',
            'icon_svg': 'celebrity',
            'primary_color': '#eab308',
            'secondary_color': '#ca8a04',
            'icon_bg_color_1': '#fef9c3',
            'icon_bg_color_2': '#fef08a',
            'order': 12,
        },
    ]
    
    # Criar os temas
    for theme_data in root_themes:
        # Verifica se o tema já existe
        if not Theme.objects.filter(slug=theme_data['slug']).exists():
            Theme.objects.create(
                title=theme_data['title'],
                slug=theme_data['slug'],
                description=theme_data['description'],
                icon_svg=theme_data['icon_svg'],
                primary_color=theme_data['primary_color'],
                secondary_color=theme_data['secondary_color'],
                icon_bg_color_1=theme_data['icon_bg_color_1'],
                icon_bg_color_2=theme_data['icon_bg_color_2'],
                order=theme_data['order'],
                active=True,
                parent=None,  # Temas raiz não têm parent
            )
            print(f"✅ Tema criado: {theme_data['title']}")
        else:
            print(f"⏭️  Tema já existe: {theme_data['title']}")


def reverse_create_root_themes(apps, schema_editor):
    """
    Remove os temas raiz criados (para reversão da migração)
    """
    Theme = apps.get_model('quizzes', 'Theme')
    
    slugs = [
        'esportes',
        'entretenimento-midia',
        'jogos',
        'ciencia-tecnologia',
        'historia',
        'geografia',
        'arte-cultura',
        'comida-bebida',
        'natureza-animais',
        'politica-sociedade',
        'curiosidades-gerais',
        'celebridades-personalidades',
    ]
    
    for slug in slugs:
        Theme.objects.filter(slug=slug, parent__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0013_add_theme_custom_colors'),
    ]

    operations = [
        migrations.RunPython(create_root_themes, reverse_create_root_themes),
    ]
