# Generated by Django 5.2.7 on 2025-10-18 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0014_change_theme_primary_key_to_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="theme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="quizzes.theme",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="theme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quizzes",
                to="quizzes.theme",
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Tema pai (deixe vazio para categoria principal)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="quizzes.theme",
            ),
        ),
    ]
