# Generated by Django 5.2.7 on 2025-10-13 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0014_setup_root_themes'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='language',
            field=models.CharField(choices=[('pt-BR', 'Português (Brasil)'), ('en', 'English'), ('es', 'Español'), ('fr', 'Français'), ('de', 'Deutsch'), ('it', 'Italiano')], default='pt-BR', help_text='Idioma do quiz', max_length=10),
        ),
        migrations.AddField(
            model_name='theme',
            name='language',
            field=models.CharField(choices=[('pt-BR', 'Português (Brasil)'), ('en', 'English'), ('es', 'Español'), ('fr', 'Français'), ('de', 'Deutsch'), ('it', 'Italiano')], default='pt-BR', help_text='Idioma do tema', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(max_length=500, verbose_name='URL da Imagem (use Cloudinary)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.URLField(blank=True, help_text='URL da imagem da pergunta (opcional - use Cloudinary)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='card_background_image',
            field=models.URLField(blank=True, help_text='URL da imagem de background do CARD/CAIXA do tema (use Cloudinary)', max_length=500, null=True),
        ),
    ]
