# Generated by Django 5.2.7 on 2025-10-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0015_add_language_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='icon_svg',
        ),
        migrations.AddField(
            model_name='theme',
            name='icon',
            field=models.URLField(blank=True, help_text='URL da imagem do ícone (PNG, SVG, etc - use Cloudinary)', max_length=500, null=True),
        ),
    ]
