# Generated by Django 5.2.7 on 2025-10-15 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0016_rename_icon_svg_to_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='theme',
            unique_together={('slug', 'language')},
        ),
    ]
