# Generated by Django 5.2.7 on 2025-10-15 00:34

from django.db import migrations, models


def copy_language_to_country(apps, schema_editor):
    """Copia dados de language para country"""
    Theme = apps.get_model('quizzes', 'Theme')
    Quiz = apps.get_model('quizzes', 'Quiz')
    
    # Copiar language para country nos temas
    for theme in Theme.objects.all():
        theme.country = theme.language
        theme.save()
    
    # Copiar language para country nos quizzes
    for quiz in Quiz.objects.all():
        quiz.country = quiz.language
        quiz.save()


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0017_alter_theme_slug_alter_theme_unique_together'),
    ]

    operations = [
        # 1. Adicionar campo country aos modelos
        migrations.AddField(
            model_name='theme',
            name='country',
            field=models.CharField(choices=[('en-US', '🇺🇸 United States'), ('en-CA', '🇨🇦 Canada'), ('es-MX', '🇲🇽 Mexico'), ('en-GB', '🇬🇧 United Kingdom'), ('de-DE', '🇩🇪 Germany'), ('fr-FR', '🇫🇷 France'), ('es-ES', '🇪🇸 Spain'), ('it-IT', '🇮🇹 Italy'), ('nl-NL', '🇳🇱 Netherlands'), ('sv-SE', '🇸🇪 Sweden'), ('no-NO', '🇳🇴 Norway'), ('pl-PL', '🇵🇱 Poland'), ('pt-PT', '🇵🇹 Portugal'), ('en-IN', '🇮🇳 India'), ('en-PH', '🇵🇭 Philippines'), ('id-ID', '🇮🇩 Indonesia'), ('ja-JP', '🇯🇵 Japan'), ('ko-KR', '🇰🇷 South Korea'), ('th-TH', '🇹🇭 Thailand'), ('vi-VN', '🇻🇳 Vietnam'), ('en-AU', '🇦🇺 Australia'), ('en-NZ', '🇳🇿 New Zealand'), ('pt-BR', '🇧🇷 Brazil'), ('es-AR', '🇦🇷 Argentina'), ('es-CO', '🇨🇴 Colombia')], default='pt-BR', help_text='País do tema', max_length=10),
        ),
        migrations.AddField(
            model_name='quiz',
            name='country',
            field=models.CharField(choices=[('en-US', '🇺🇸 United States'), ('en-CA', '🇨🇦 Canada'), ('es-MX', '🇲🇽 Mexico'), ('en-GB', '🇬🇧 United Kingdom'), ('de-DE', '🇩🇪 Germany'), ('fr-FR', '🇫🇷 France'), ('es-ES', '🇪🇸 Spain'), ('it-IT', '🇮🇹 Italy'), ('nl-NL', '🇳🇱 Netherlands'), ('sv-SE', '🇸🇪 Sweden'), ('no-NO', '🇳🇪 Norway'), ('pl-PL', '🇵🇱 Poland'), ('pt-PT', '🇵🇹 Portugal'), ('en-IN', '🇮🇳 India'), ('en-PH', '🇵🇭 Philippines'), ('id-ID', '🇮🇩 Indonesia'), ('ja-JP', '🇯🇵 Japan'), ('ko-KR', '🇰🇷 South Korea'), ('th-TH', '🇹🇭 Thailand'), ('vi-VN', '🇻🇳 Vietnam'), ('en-AU', '🇦🇺 Australia'), ('en-NZ', '🇳🇿 New Zealand'), ('pt-BR', '🇧🇷 Brazil'), ('es-AR', '🇦🇷 Argentina'), ('es-CO', '🇨🇴 Colombia')], default='pt-BR', help_text='País do quiz', max_length=10),
        ),
        
        # 2. Copiar dados de language para country
        migrations.RunPython(copy_language_to_country, reverse_code=migrations.RunPython.noop),
        
        # 3. Remover unique_together antigo
        migrations.AlterUniqueTogether(
            name='theme',
            unique_together=set(),
        ),
        
        # 4. Remover campo language
        migrations.RemoveField(
            model_name='theme',
            name='language',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='language',
        ),
        
        # 5. Adicionar novo unique_together
        migrations.AlterUniqueTogether(
            name='theme',
            unique_together={('slug', 'country')},
        ),
    ]
