# Generated by Django 5.2.7 on 2025-10-15 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0018_remove_quiz_language_alter_theme_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='country',
            field=models.CharField(choices=[('en-US', '🇺🇸 United States'), ('en-CA', '🇨🇦 Canada'), ('es-MX', '🇲🇽 Mexico'), ('en-GB', '🇬🇧 United Kingdom'), ('de-DE', '🇩🇪 Germany'), ('fr-FR', '🇫🇷 France'), ('es-ES', '🇪🇸 Spain'), ('it-IT', '🇮🇹 Italy'), ('nl-NL', '🇳🇱 Netherlands'), ('sv-SE', '🇸🇪 Sweden'), ('no-NO', '🇳🇴 Norway'), ('pl-PL', '🇵🇱 Poland'), ('pt-PT', '🇵🇹 Portugal'), ('en-IN', '🇮🇳 India'), ('en-PH', '🇵🇭 Philippines'), ('id-ID', '🇮🇩 Indonesia'), ('ja-JP', '🇯🇵 Japan'), ('ko-KR', '🇰🇷 South Korea'), ('th-TH', '🇹🇭 Thailand'), ('vi-VN', '🇻🇳 Vietnam'), ('en-AU', '🇦🇺 Australia'), ('en-NZ', '🇳🇿 New Zealand'), ('pt-BR', '🇧🇷 Brazil'), ('es-AR', '🇦🇷 Argentina'), ('es-CO', '🇨🇴 Colombia')], default='pt-BR', help_text='País do quiz', max_length=10),
        ),
    ]
